import React from 'react';

const FAQ = () => {
  const faqs = [
    {
      question: 'What are credits and how do they work?',
      answer: 'Credits are our virtual currency used to access AI features. Different features require different amounts of credits. Credits never expire and you can purchase more at any time.'
    },
    {
      question: 'Can I try the service before buying credits?',
      answer: 'Yes! New users get 50 free credits to test our features. This allows you to experience our AI story generation and voice creation tools before making a purchase.'
    },
    {
      question: 'How many credits do I need for a typical novel?',
      answer: 'A typical novel chapter uses about 10-15 credits for AI generation. Character creation uses about 20 credits per character. We recommend starting with our 500 credit package for a full novel.'
    },
    {
      question: 'Are the generated stories unique?',
      answer: 'Yes, all stories generated by our AI are unique and original. You retain full rights to any content created using our platform.'
    }
  ];

  return (
    <div className="py-20 bg-gray-50">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-600">
            Everything you need to know about our service
          </p>
        </div>

        <div className="space-y-8">
          {faqs.map((faq, index) => (
            <div key={index} className="bg-white rounded-xl shadow-lg p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-2">
                {faq.question}
              </h3>
              <p className="text-gray-600">
                {faq.answer}
              </p>
            </div>
          ))}
        </div>

        <div className="text-center mt-12">
          <p className="text-gray-600 mb-4">Still have questions?</p>
          <button className="px-6 py-3 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors">
            Contact Support
          </button>
        </div>
      </div>
    </div>
  );
}

export default FAQ;